package w.p.j;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-18T09:22:55.699+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://j.p.w/", name = "ICXFTypeTest")
@XmlSeeAlso({ObjectFactory.class})
public interface ICXFTypeTest {

    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://j.p.w/", className = "w.p.j.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://j.p.w/", className = "w.p.j.AddStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        w.p.j.Student arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStudentMap", targetNamespace = "http://j.p.w/", className = "w.p.j.GetStudentMap")
    @ResponseWrapper(localName = "getStudentMapResponse", targetNamespace = "http://j.p.w/", className = "w.p.j.GetStudentMapResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public w.p.j.GetStudentMapResponse.Return getStudentMap();

    @WebMethod
    @RequestWrapper(localName = "getStuList", targetNamespace = "http://j.p.w/", className = "w.p.j.GetStuList")
    @ResponseWrapper(localName = "getStuListResponse", targetNamespace = "http://j.p.w/", className = "w.p.j.GetStuListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<w.p.j.Student> getStuList();

    @WebMethod
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://j.p.w/", className = "w.p.j.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://j.p.w/", className = "w.p.j.GetStudentByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public w.p.j.Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
