package w.p.j.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import w.p.j.IHello;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-18T08:26:32.967+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "HelloServiceImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/ws/cxf?wsdl",
                  targetNamespace = "http://impl.j.p.w/") 
public class HelloServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.j.p.w/", "HelloServiceImplService");
    public final static QName HelloServiceImplPort = new QName("http://impl.j.p.w/", "HelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/ws/cxf?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/ws/cxf?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHello getHelloServiceImplPort() {
        return super.getPort(HelloServiceImplPort, IHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHello getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServiceImplPort, IHello.class, features);
    }

}
