package spring.dao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-19T10:11:13.059+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://dao.spring/", name = "OrderWs")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderWs {

    @WebMethod
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://dao.spring/", className = "spring.dao.GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://dao.spring/", className = "spring.dao.GetOrderByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public spring.dao.Order getOrderById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
