package w.p.j.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import w.p.j.ICXFTypeTest;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-18T19:39:50.229+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "CXFTypeImplService", 
                  wsdlLocation = "http://127.0.0.1:9999/ws/cxf?wsdl",
                  targetNamespace = "http://impl.j.p.w/") 
public class CXFTypeImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.j.p.w/", "CXFTypeImplService");
    public final static QName CXFTypeImplPort = new QName("http://impl.j.p.w/", "CXFTypeImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9999/ws/cxf?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CXFTypeImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:9999/ws/cxf?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CXFTypeImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CXFTypeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CXFTypeImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CXFTypeImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CXFTypeImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CXFTypeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ICXFTypeTest
     */
    @WebEndpoint(name = "CXFTypeImplPort")
    public ICXFTypeTest getCXFTypeImplPort() {
        return super.getPort(CXFTypeImplPort, ICXFTypeTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICXFTypeTest
     */
    @WebEndpoint(name = "CXFTypeImplPort")
    public ICXFTypeTest getCXFTypeImplPort(WebServiceFeature... features) {
        return super.getPort(CXFTypeImplPort, ICXFTypeTest.class, features);
    }

}
